jobs:
  labels:
    secrets:
      GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
      GH_APP_NAME: ${{ secrets.GH_APP_NAME }}
    uses: MinecraftForge/SharedActions/.github/workflows/issue_actions.yml@main
name: Issue actions
on:
  repository_dispatch:
    types: trigger-ga___issues.yml
permissions:
  contents: read
  discussions: write
  issues: write
  pull-requests: write
