jobs:
  upload_payload:
    name: Upload payload
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: payload
        path: ${{ github.event_path }}
name: PR Review Comment
on:
  repository_dispatch:
    types: trigger-ga___pull_request_review_comment.yml
